services:
  - type: web
    name: javafl-api
    env: java
    buildCommand: "chmod +x mvnw && ./mvnw clean package -DskipTests"
    startCommand: "java -Dserver.port=$PORT -jar target/JavaFL-0.0.1-SNAPSHOT.jar"
